name: sonoramente
description: "Um aplicativo de cuidado emocional em √°udio."
publish_to: 'none'

version: 1.0.15+16

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # B√°sicos
  http: ^1.2.0
  provider: ^6.1.2
  intl: ^0.19.0
  image_picker: ^1.0.7

  # √Åudio
  just_audio: ^0.9.36
  audioplayers: ^6.0.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.5
  cloud_functions: ^4.6.5
  secure_application: ^4.1.0

  # Login com Google
  google_sign_in: ^6.2.1

  # Seguran√ßa
  screen_protector: ^1.4.2

  # √çcones iOS
  cupertino_icons: ^1.0.8

  # Links externos
  url_launcher: ^6.2.5

  # Compras no app
  in_app_purchase: ^3.1.11

  # üì± Device info (USADO EM RUNTIME)
  device_info_plus: ^10.1.0

  # üíæ Storage local (USADO EM RUNTIME)
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^4.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png
